services:
  - type: web
    name: ipo-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ipo_project.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: your-backend-name.onrender.com
