# Generated by Django 5.2.3 on 2025-06-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipo',
            old_name='date',
            new_name='ipo_date',
        ),
        migrations.AlterField(
            model_name='ipo',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
